// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRdTIN51IJiEX38axblgyPV7rXjQYc2M4',
    appId: '1:372427916737:web:48d5f0a41cb6bcf575db40',
    messagingSenderId: '372427916737',
    projectId: 'bitescan-96240',
    authDomain: 'bitescan-96240.firebaseapp.com',
    storageBucket: 'bitescan-96240.appspot.com',
    measurementId: 'G-5MHCFEG7BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmpfQk62KDB0dXRdI6-O0bSsLUW56lyY',
    appId: '1:372427916737:android:a27e80a17a3d4b7375db40',
    messagingSenderId: '372427916737',
    projectId: 'bitescan-96240',
    storageBucket: 'bitescan-96240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pebUhpFDoQwuRq8UBFq6ECYQy6BgYmg',
    appId: '1:372427916737:ios:bd61e48132a2bb5075db40',
    messagingSenderId: '372427916737',
    projectId: 'bitescan-96240',
    storageBucket: 'bitescan-96240.appspot.com',
    iosBundleId: 'com.example.bitescan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-pebUhpFDoQwuRq8UBFq6ECYQy6BgYmg',
    appId: '1:372427916737:ios:ca9c279c64390d9975db40',
    messagingSenderId: '372427916737',
    projectId: 'bitescan-96240',
    storageBucket: 'bitescan-96240.appspot.com',
    iosBundleId: 'com.example.bitescan.RunnerTests',
  );
}
